### ISSUE TITLE
Unable to close navigation bar when a menu item (in the nav bar) is clicked.

### ISSUE THREAD

**Issue by sankari123** [JoanClaret/slide-and-swipe-menu#18]
Thanks for your code.Very easy to follow. I have an issue. In the navigation  bar  ( where hand image is displayed) I have listed few menu items such as Home, Archives, Login and so on. When a menu is clicked, I want the navigation bar to  close . But the navigation does not hide but expects the user to swipe. Pl help me

**Comment by JoanClaret** [comment]
Hi there, thanks for your comments

this is not an expected functionality, since normally the link you clicked inside the navigation bar will redirect to another page. there you'll find the navigation closed.

aside of this, you can close / open the navigation by calling the function `slideAndSwipe`
so maybe (as an easy solution) you can make something like this
```
<script>
  $(document).ready(function() {
    $('.your-nav-bar a').slideAndSwipe();
  });
</script>
```

like so, all links located in `.your-nav-bar` will close the navigation bar. 
hope this solution fits with your needs.

cheers
J

**Comment by sankari123** [comment]
Thanks for your quick reply. i'm sorry. but your solution s not working.  I'm calling a javascript function which should perform 2 fns 1. close nav bar. 2. open login form in main screen. 

Ass per this code (after adding **class="ssm-toggle-nav"**,) the nav bar is closed but login function is not called.
                    
          <ul>
              <li><a href="javascript: login();" class="ssm-toggle-nav">Login</a></li>
              <li><a href="#">Archives</a></li>
               <li><a href="#">Feedback</a></li>
          </ul>
         </nav>
