### ISSUE TITLE
Remove overflow:hidden from <html>

### ISSUE THREAD

**Issue by dsoldera** [JoanClaret/slide-and-swipe-menu#6]
Hi,

I´ve checked than this plugin is inserting a overflow:hidden at the html tag to remove the page scrool.

Is there any params to insert to remove this option, without changing the source?

Thanks

Danielle

**Comment by JoanClaret** [comment]
no, there is no way.
as you said, this overflow is used to hide scroll when navigation is outside of the viewport, so i think is     absolutely necessary.

**Comment by dsoldera** [comment]
ok. No problem. Thanks!

**Comment by atechni** [comment]
ok

2016-07-20 19:06 GMT+01:00 Dani Soldera notifications@github.com:

**Comment by cedricve** [comment]
Nice job Joan! However I would like to have this removed as well, it's annoying that the page gets back to the top, and that a user doesn't has the chance to navigate further on the page.

Maybe this should be an option?

**Comment by JoanClaret** [comment]
@cedricve The page goes to the top because of the click, not of the overflow hidden. 
As a permanent solution, i will add `e.preventDefault();` in the open navigation function.
Meanwhile, you can simply add `<a href="javascript:void(0);"></a>` to prevent the annoying scroll.
This should work.
Thanks for pointing out the bug. i appreciate it!

**Comment by JoanClaret** [comment]
Hi folks

@cedricve : update your js file. the annoying scroll should be fixed.
@dsoldera , @atechni : i managed to avoid the overflow:hidden using a class instead of add styles programatically in the html. Hope it helps you.
