### ISSUE TITLE
Cannot find module 'slideAndSwipe'

### ISSUE THREAD

**Issue by nkeena** [JoanClaret/slide-and-swipe-menu#8]
When using browserify `require('slideAndSwipe')` it returns a cannot find module error.

**Comment by JoanClaret** [comment]
There was a mistake in package.json file.
It should be working now.

**Comment by JoanClaret** [comment]
i found another mistake: you should require like this:
`require('slide-and-swipe-menu');`

**Comment by nabil1337** [comment]
Hi!

This was actually still a thing for me.

The problem is that you export `slideAndSwipe`, which is only defined inside a closure.

Fix: Instead of `var slideAndSwipe =` inside the closure, write `slideAndSwipe =`. This also makes it necessary to declare the variable _above_ the closure (`var slideAndSwipe;`). This fixed the issue for me, but then there was another one: The closure gets called with `window.jQuery || window.$`, which were not defined, since I was using browserify.

Maybe a function like this could help (I only tested it with browserify):

```
function getJquery() {
    if (typeof module !== 'undefined' && module.exports) {
        return require('jquery');
    } else if (window.jQuery || window.$) {
        return window.jQuery || window.$;
    } else {
        throw new Error('Can\'t find jQuery');
    }
}
```

Then simply use a call to this function instead of `window.jQuery || window.$` for the closure and it should work.
